# Generated by Django 4.0.2 on 2022-03-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_image', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('media_video', models.FileField(blank=True, null=True, upload_to='vid/')),
            ],
        ),
        migrations.AlterField(
            model_name='contacto_in',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
